### PR TITLE
Add documentation for direct client usage

### PR DESCRIPTION
**Pull request by ianfixes**
## Summary

CI/CD pipelines might already be written in Ruby, so it would be more efficient to use the class from the gem instead of calling the shell just to hit a command-line wrapper 

* Add `yard` to development gems to get a local preview of the documentation that is automatically generated/hosted at https://rubydoc.info/gems/gemfury
* Resolve `yard` warnings about undocumentable code by replacing `attr_accessor *Configuration::VALID_OPTIONS_KEYS` with the full list of attributes and their docstring comments.  Since both `Configuration` and `Client` used these attributes identically, I factored these into a new module called `ConfigurationAttributes` that both classes now include.
* Add parameter and return types / descriptions to the documentation of the client and configuration
* Refer to "Artifacts" instead of "gems", in the docstring comments since (if I'm understanding the code correctly) this client is able to manipulate packages in JS, Python, etc., not just Ruby
* Update README to point to online documentation
* Run `yard` as part of CI just to ensure that it works (since that is what `rubydoc.info` will do); for ruby 1.x, this will fail because yard doesn't install -- handle that case too.

## Testing
All tests pass and (to my knowledge) no public APIs have been broken.

## Example of updated documentation:
Screen Shot 2020-06-02 at 12 58 13 AM

### CODE REVIEW

**Comment by rykov** [comment]
Thank you @ianfixes for the updates. The documentation fixes look great. Is there any way to separate that from the configuration refactoring? I still have a few questions about that.

**Comment by ianfixes** [comment]
> Is there any way to separate [the documentation fixes] from the configuration refactoring?

Not really, the only reason I did any refactoring at all was because `yard` couldn't parse this type of shorthand syntax:

```ruby
  attr_accessor *VALID_OPTIONS_KEYS
```

So I tried to do the next best thing, which was to define all those things in a new module and then include the module.

I took the liberty of moving all the `DEFAULT_` constants into `CONFIGURATION_DEFAULTS` because I didn't want to have to double up the comments on those declarations (one for the attribute, one for the default value).  This seemed like the cleanest way.

**Comment by rykov** [comment]
@ianfixes Ok, I see what you mean about creating explicit accessors for each individual config key. 

So the aesthetic of having two configuration modules was bothering me, so I went ahead and moved the old `Configuration` functionality directly into `Gemfury`, and renamed your `ConfigurationAttirbutes` to `Configuration`. What do you think? Am I missing something? https://github.com/rykov/gemfury/commit/1ca5d56a3310322fa1395d4f2278807a1c0d1716

**Comment by ianfixes** [comment]
That sounds awesome!  I didn't feel comfortable making that change as a new contributor, but I absolutely agree with it.

**Comment by ianfixes** [comment]
Do you want me to cherry-pick 1ca5d56a3310322fa1395d4f2278807a1c0d1716 into this PR?

**Comment by rykov** [comment]
> Do you want me to cherry-pick [1ca5d56](https://github.com/gemfury/gemfury/commit/1ca5d56a3310322fa1395d4f2278807a1c0d1716) into this PR?

Yup, go for it.

**Comment by ianfixes** [comment]
All set

**Pull request merged**
